# Generated by Django 2.1.8 on 2019-04-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postpage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='tags',
        ),
    ]
